security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: phone
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            provider: app_user_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: /admin
            logout:
                path: admin_logout
                target: admin_login

        login:
            pattern: ^/api/auth/login
            stateless: true
            json_login:
                check_path: /api/auth/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                username_path: phone
                password_path: password

        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            jwt: ~
            logout:
                path: api_logout
            refresh_jwt:
                check_path: /api/auth/refresh

        external_api:
            pattern: ^/external_api
            stateless: true
            security: true
            custom_authenticator: App\Security\ExternalApiAuthenticator

    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER, ROLE_MANAGER ]
        ROLE_MANAGER: [ ROLE_USER ]

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_MANAGER }
        - { path: ^/api/product, methods: [ POST, PUT, DELETE ], roles: ROLE_MANAGER }
        - { path: ^/api/auth/(login|refresh), roles: PUBLIC_ACCESS }
        - { path: ^/api/auth/logout, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/(basket|order), roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api, roles: PUBLIC_ACCESS }